#platform :ios, ‘8.0’

target "test-001" do
#xcodeproj './test-001.xcodeproj'


#AFNetworking 网络库
platform :ios, '8.0'
pod "AFNetworking", "~> 3.0"

#ReactuveCocoa
#pod 'ReactiveCocoa', '5.0.0-rc.1'
pod 'ReactiveCocoa'

#SDWebImage
#platform :ios, '7.0'
pod 'SDWebImage', '~> 3.8'

#JSPatch
#platform :ios, '6.0'
pod 'JSPatch'

end
